---
title: "Untitled"
output: html_document
date: "2025-05-06"
---



```{r reprex_example_gridtitles}
# https://stackoverflow.com/questions/79607800/how-to-add-titles-to-plots-in-openrepgrid

#load library
library(OpenRepGrid)

#load an example grid
participant_grid <- fbb2003 

#Create dendogram for constructs with participant name
## prints title 
cluster(participant_grid, along=1, main="Participant Name")


#Create bertin diagram for constructs/elements w/ participant name
## does not print title 
bertinCluster(participant_grid, main= "Participant Name")

#Create PCA biplot w/ participant name 
##does not print title 
OpenRepGrid::biplot2d(participant_grid, main = "Participant Name — 2D Biplot")



bertinCluster(participant_grid, along=1, main="Participant Name")
op <- par(fig = c(0,1,0.1,1), mai=c(0,0,0.2,0), new = TRUE)
title("Participant Name")
```

```{r second reprex}

#load library
library(OpenRepGrid)

#load an example grid
participant_grid <- p15 

bertinCluster(participant_grid, along=1,
              cex = 1, lab.cex = 1
              )
op <- par(fig = c(0,1,0.1,1), mai=c(0,0,0.15,0), adj=0, new = TRUE)
title("Participant Name")

```

```{r wip clustering multigrids}

## grids w/ same constructs, same ratings 
## constructs treated as unique rather than the same 
a <- bindConstructs(fbb2003, fbb2003)
cluster(a, along=1, align=FALSE)
## ^duplicates constructs


## grids w/ same constructs but different ratings 
a <- fbb2003
b <- permuteGrid(a,along=1)
supergrid <- bindConstructs(a,b)

## clustering w/ alignment shows how constructs treated as unique; some are reversed 
cluster(supergrid, along=1)

## clustering w/o alignment shows how constructs treated as unique; 
## despite the differing ratings, the structure is reflected??
cluster(supergrid, along=1, align=FALSE)


## NEXT STEP:: figure out what hclust() does (that's the underlying function)
## and how hclust() handles observation data 

## NEXT STEP :: see Bell (zotero)
##https://www.tandfonline.com/doi/epdf/10.1080/10720530050130111?needAccess=true
## and fransella book (hardcopy) on multiple grids 

## NEXT STEP (lmer) :: email Mark Heckmann 
## see some example of how his lmer software was used 
## see if there are citations to the paper that demonstrate the model
## if not email him to ask about model structure 

## NEXT STEP :: explore EXPLORATORY FACTOR ANALYSIS on the coded data

```

### PCA plot options
```{r}

biplot2d(boeker) # biplot of boeker data
 biplot2d(boeker, c.lines = T) # add construct lines
 biplot2d(boeker, center = 2) # with column centering
 biplot2d(boeker, center = 4) # midpoint centering
 biplot2d(boeker, normalize = 1) # normalization of constructs
 
 biplot2d(boeker, dim = 2:3) # plot 2nd and 3rd dimension
 biplot2d(boeker, dim = c(1, 4)) # plot 1st and 4th dimension
 
 biplot2d(boeker, g = 1, h = 1) # assign singular values to con. & elem.
 biplot2d(boeker, g = 1, h = 1, center = 1) # row centering (Slater)
 biplot2d(boeker, g = 1, h = 1, center = 4) # midpoint centering (ESA)
 
 biplot2d(boeker, e.point.color = "red", c.label.color = "blue") # change colors
 biplot2d(boeker, c.point.color = c("white", "darkred")) # mapped onto color range
 
 biplot2d(boeker, unity = T) # scale con. & elem. to equal length
 biplot2d(boeker, unity = T, scale.e = .5) # scaling factor for element vectors
 
 biplot2d(boeker, e.labels.show = F) # do not show element labels
 biplot2d(boeker, e.labels.show = c(1, 2, 4)) # show labels for elements 1, 2 and 4
 biplot2d(boeker, e.points.show = c(1, 2, 4)) # only show elements 1, 2 and 4
 biplot2d(boeker, c.labels.show = c(1:4)) # show constructs labels 1 to 4
 biplot2d(boeker, c.labels.show = c(1:4)) # show constructs labels except 1 to 4
 
 biplot2d(boeker, e.cex.map = 1) # change size of texts for elements
 biplot2d(boeker, c.cex.map = 1) # change size of texts for constructs
 
 biplot2d(boeker, g = 1, h = 1, c.labels.inside = F) # constructs inside the plot
 biplot2d(boeker,
   g = 1, h = 1, c.labels.inside = T, # different margins and elem. color
   mai = c(0, 0, 0, 0), e.color = "red"
 )
 
 biplot2d(boeker, strokes.x = .3, strokes.y = .05) # change length of strokes
 
 biplot2d(boeker, flipaxes = c(T, F)) # flip x axis
 biplot2d(boeker, flipaxes = c(T, T)) # flip x and y axis
 
 biplot2d(boeker, outer.positioning = F) # no positioning of con.-labels
 
 biplot2d(boeker, c.labels.devangle = 20) # only con. within 20 degree angle

```
